dist: bionic
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: g++
      addons:
      env: BUILD_SYSTEM=cmake
    - os: linux
      compiler: clang++
      addons:
      env: BUILD_SYSTEM=cmake
    - os: linux
      compiler: g++
      addons:
      env: BUILD_SYSTEM=qmake
    - os: linux
      compiler: clang++
      addons:
      env: BUILD_SYSTEM=qmake

addons:
  apt:
    packages:
    - qt5-default
    - libqt5opengl5-dev
    - rpm

script:
  - ${BUILD_SYSTEM} --version
  - ${CXX} --version
  - echo CXXFLAGS=${CXXFLAGS}
  - mkdir build && cd build
  - if [[ "${BUILD_SYSTEM}" == "cmake" ]] ; then
      cmake .. ;
    elif [[ "${BUILD_SYSTEM}" == "qmake" ]] ; then
      qmake .. ;
    fi
  - make
  - if [[ "${BUILD_SYSTEM}" == "cmake" ]] ; then make package ; fi

