dist: bionic
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: g++
      addons:
      env: BUILD_SYSTEM=cmake BUILD_TYPE=Debug
    - os: linux
      compiler: g++
      addons:
      env: BUILD_SYSTEM=cmake BUILD_TYPE=Release
    - os: linux
      compiler: clang++
      addons:
      env: BUILD_SYSTEM=cmake BUILD_TYPE=Debug
    - os: linux
      compiler: clang++
      addons:
      env: BUILD_SYSTEM=cmake BUILD_TYPE=Release
    - os: linux
      compiler: g++
      addons:
      env: BUILD_SYSTEM=qmake
    - os: linux
      compiler: clang++
      addons:
      env: BUILD_SYSTEM=qmake

addons:
  apt:
    packages:
    - qt5-default
    - libqt5opengl5-dev
    - rpm

script:
  - ${BUILD_SYSTEM} --version
  - ${CXX} --version
  - echo CXXFLAGS=${CXXFLAGS}
  - mkdir build && cd build
  - [[ "${BUILD_SYSTEM}" = "cmake" ]] && cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - [[ "${BUILD_SYSTEM}" = "qmake" ]] && qmake ..
  - make
  - [[ "${BUILD_SYSTEM}" = "cmake" ]] && make package

